### ISSUE TITLE
Report spelling errors as info rather than warnings

### ISSUE THREAD

**Issue by AspieSoft** [tekumara/typos-vscode#17]
In the vscode extension settings, if I set the log level to "info", it continues to report spelling errors as warnings.

**Comment by tekumara** [comment]
Interesting, could you share a screenshot? I'm not sure how to replicate this behaviour.

**Comment by AspieSoft** [comment]
In this extension, The setting is set to "info", but still returns a "warning" (yellow).

![vscode-typos-spell-checker](https://github.com/tekumara/typos-vscode/assets/62117732/e55005d1-3a66-43e2-a479-79bcf69e162f)

In the code spell checker extension, I get the report as "info" (blue)

![vscode-code-spell-checker](https://github.com/tekumara/typos-vscode/assets/62117732/454cb2dd-8401-4ffa-97cd-ce7b47ff1ba8)

I was originally using the code spell checker extension, but went looking for something with ess false positives, and your extension seems to do great at that. Having spelling errors marked as "info" instead of as a "warning", makes it easier to separate programing warnings from spelling mistakes.

This issue is also consistent under the "problems" tab of vscode.

**Comment by tekumara** [comment]
Ah gotcha. So `Typos: Log Level` refers to the logging that appears in the `Output -> Typos` pane.

It sounds like you'd like to configure the [diagnostic severity](https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnostic:~:text=diagnostic%20severities) which isn't currently supported but is something that I'd be happy to add.

**Comment by AspieSoft** [comment]
Ok, that makes sense. Thank you.

**Comment by tekumara** [comment]
@AspieSoft I've released [v0.1.7](https://github.com/tekumara/typos-vscode/releases/tag/v0.1.7) which has the new setting `typos.diagnosticSeverity`. You can use this to configure diagnostics to display as `Information` instead of `Warning`.

**Comment by fusillicode** [comment]
I'm really sorry for bothering you all on this closed issue but I didn't find a better place where to ask 😞 

Question: the diagnostics levels cannot be customized on NeoVim via `nvim-lspconfig`, only on VSCode, right?
Asking because [I kind of tried everything](https://github.com/fusillicode/dotfiles/blob/f88964ee7334ba42c9fa0738dfa33a729d06f12c/nvim/lua/mason-tools.lua#L49-L63) but didn't managed to make the diagnostics being reported as anything different from errors.

Sorry for the dumb question and once again for the bother.

P.S: thank you really a lot for all you amazing work! 🙇‍♂️

**Comment by tekumara** [comment]
Hey @fusillicode it should be possible on any editor than can provide initialisation options to the lsp server. I'm sorry I don't know how to do that with neovim but if you find a way let us know 😊

**Comment by fusillicode** [comment]
@tekumara thanks really a lot for the quick feedback! 🙇‍♂️ 

If I make it to work with Neovim I'll come back with the solution and maybe open a PR to document the thing! 👍 

Thanks again for everything! ♾️ 🙇‍♂️

**Comment by fusillicode** [comment]
@nghialm269 thanks for the feedback but unfortunately it's not working on my side https://github.com/fusillicode/dotfiles/blob/39fa7e51d89924091703c9ebc68897e8cec5a468/nvim/lua/mason-tools.lua#L49-L53 🥲

**Comment by nghialm269** [comment]
@fusillicode: here is the mini config file from nvim-lspconfig:

```lua
local on_windows = vim.loop.os_uname().version:match("Windows")

local function join_paths(...)
	local path_sep = on_windows and "\\" or "/"
	local result = table.concat({ ... }, path_sep)
	return result
end

vim.cmd([[set runtimepath=$VIMRUNTIME]])

local temp_dir = vim.loop.os_getenv("TEMP") or "/tmp"

vim.cmd("set packpath=" .. join_paths(temp_dir, "nvim", "site"))

local package_root = join_paths(temp_dir, "nvim", "site", "pack")
local lspconfig_path = join_paths(package_root, "test", "start", "nvim-lspconfig")

if vim.fn.isdirectory(lspconfig_path) ~= 1 then
	vim.fn.system({ "git", "clone", "https://github.com/neovim/nvim-lspconfig", lspconfig_path })
end

vim.lsp.set_log_level("trace")
require("vim.lsp.log").set_format_func(vim.inspect)
local nvim_lsp = require("lspconfig")
local on_attach = function(_, bufnr)
	local function buf_set_option(...)
		vim.api.nvim_buf_set_option(bufnr, ...)
	end

	buf_set_option("omnifunc", "v:lua.vim.lsp.omnifunc")

	-- Mappings.
	local opts = { buffer = bufnr, noremap = true, silent = true }
	vim.keymap.set("n", "gD", vim.lsp.buf.declaration, opts)
	vim.keymap.set("n", "gd", vim.lsp.buf.definition, opts)
	vim.keymap.set("n", "K", vim.lsp.buf.hover, opts)
	vim.keymap.set("n", "gi", vim.lsp.buf.implementation, opts)
	vim.keymap.set("n", "<C-k>", vim.lsp.buf.signature_help, opts)
	vim.keymap.set("n", "<space>wa", vim.lsp.buf.add_workspace_folder, opts)
	vim.keymap.set("n", "<space>wr", vim.lsp.buf.remove_workspace_folder, opts)
	vim.keymap.set("n", "<space>wl", function()
		print(vim.inspect(vim.lsp.buf.list_workspace_folders()))
	end, opts)
	vim.keymap.set("n", "<space>D", vim.lsp.buf.type_definition, opts)
	vim.keymap.set("n", "<space>rn", vim.lsp.buf.rename, opts)
	vim.keymap.set("n", "gr", vim.lsp.buf.references, opts)
	vim.keymap.set("n", "<space>e", vim.diagnostic.open_float, opts)
	vim.keymap.set("n", "[d", vim.diagnostic.goto_prev, opts)
	vim.keymap.set("n", "]d", vim.diagnostic.goto_next, opts)
	vim.keymap.set("n", "<space>q", vim.diagnostic.setloclist, opts)
end

-- Add the server that troubles you here
local name = "typos_lsp"
local cmd = { '/home/nghialm/.local/share/nvim/mason/bin/typos-lsp' } -- needed for elixirls, lua_ls, omnisharp
if not name then
	print("You have not defined a server name, please edit minimal_init.lua")
end
if not nvim_lsp[name].document_config.default_config.cmd and not cmd then
	print([[You have not defined a server default cmd for a server
    that requires it please edit minimal_init.lua]])
end

nvim_lsp[name].setup({
	cmd = cmd,
	on_attach = on_attach,
	init_options = {
		diagnosticSeverity = 'Warning',
	},
})

-- test typo symbo
```

save to `mini.lua`, change the path to `typos-lsp` and run neovim with: `nvim --clean -u mini.lua mini.lua`

you should see the warning typo in the last line (`symbo`)

**Comment by fusillicode** [comment]
@nghialm269 thanks so much for coming back so quickly and with that extensive example! ♾️ 🙇‍♂️ 
I think now I understand the issue 🙏 
It's just a matter of fixing my setup 🥲 
Thanks again!

**Comment by fusillicode** [comment]
To anyone who will bump into this, [my issue](https://github.com/tekumara/typos-vscode/issues/17#issuecomment-1831416474) was fixed thanks to [this](https://github.com/tekumara/typos-vscode/issues/17#issuecomment-1832292795).

More specifically the `diagnosticSeverity` must be passed to the LSP (`typos`) as part of `init_options`, not `settings` (https://github.com/neovim/nvim-lspconfig/blob/39546f730bdff8eccf7cec344cfce694f19ac908/CONTRIBUTING.md?plain=1#L39).

I managed to do this ☝️ like [this](https://github.com/fusillicode/dotfiles/commit/28a1eb9d8745779f1c85809665123e76481ec608).

♾️ thanks once again to @nghialm269 🙏 🙇‍♂️

**Comment by mawkler** [comment]
Did the config API for `diagnosticSeverity` change recently? I have successfully had it configured to be set to `hint` for a long time using [the solution above](https://github.com/tekumara/typos-lsp/issues/17#issuecomment-1832355562), but  since the last couple of days the severity is `error`, even though I haven't touched my config.

**Comment by tekumara** [comment]
The [diagnosticSeverity config here](https://github.com/tekumara/typos-lsp/blob/main/docs/neovim-lsp-config.md) is still working for me in neovim with the latest typos (0.1.33). Has something else changed with your neovim setup?

**Comment by tekumara** [comment]
The [diagnosticSeverity config here](https://github.com/tekumara/typos-lsp/blob/main/docs/neovim-lsp-config.md) is still working for me in neovim with the latest typos-lsp (0.1.33). Has something else changed with your neovim setup?

**Comment by mawkler** [comment]
It was a configuration error on my part. I had recently added this configuration as suggested by [nvim-ufo](https://github.com/kevinhwang91/nvim-ufo?tab=readme-ov-file#minimal-configuration), which was overriding my typos_lsp config:

```lua
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.foldingRange = {
  dynamicRegistration = false,
  lineFoldingOnly = true,
}

for _, ls in ipairs(require('lspconfig').util.available_servers()) do
  require('lspconfig')[ls].setup({ capabilities = capabilities })
end
```
